<?php
/**
 * AttributeType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permit.io API
 *
 * Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AttributeType Class Doc Comment
 *
 * @category Class
 * @description supported attribute primitives
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttributeType
{
    /**
     * Possible values of this enum
     */
    public const BOOL = 'bool';

    public const NUMBER = 'number';

    public const STRING = 'string';

    public const TIME = 'time';

    public const _ARRAY = 'array';

    public const JSON = 'json';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BOOL,
            self::NUMBER,
            self::STRING,
            self::TIME,
            self::_ARRAY,
            self::JSON
        ];
    }
}


