<?php
/**
 * ProgrammingLanguage
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permit.io API
 *
 * Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProgrammingLanguage Class Doc Comment
 *
 * @category Class
 * @description An enumeration.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProgrammingLanguage
{
    /**
     * Possible values of this enum
     */
    public const JAVASCRIPT = 'javascript';

    public const PYTHON = 'python';

    public const DOTNET = 'dotnet';

    public const GOLANG = 'golang';

    public const JAVA = 'java';

    public const KONG_GATEWAY = 'kong_gateway';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::JAVASCRIPT,
            self::PYTHON,
            self::DOTNET,
            self::GOLANG,
            self::JAVA,
            self::KONG_GATEWAY
        ];
    }
}


